language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - cd ..
  - git clone https://github.com/owncloud/core.git
  - mv ownnotes core/apps/
  - cd core
  - git submodule init
  - git submodule update
  - cd apps/ownnotes

script:
  - phpunit tests