language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
    - DB=sqlite BRANCH master
    - DB=sqlite BRANCH stable8

install:
  # install ocdev
  - sudo apt-get -y install python3-jinja2 python3-setuptools
  - sudo easy_install3 pip
  - sudo pip3 install ocdev
  # install owncloud
  - cd ..
  - ocdev setup core --dir owncloud --branch $BRANCH
  - cd owncloud
  - ocdev ci $DB
  # enable ownnotes
  - mv tutorial owncloud/apps/ownnotes
  - php -f console.php app:enable ownnotes

before_script:
  - cd apps/ownnotes

script:
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
  
